# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: My Ollama Config
version: 1.0.0
schema: v1

# https://docs.continue.dev/customization/models
models:
  - uses: ollama/deepseek-coder:6.7b
  - uses: ollama/llama3:8b
